# Generated by Django 5.2.11 on 2026-02-08 17:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Album",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=200, verbose_name="Titre")),
                (
                    "cover",
                    models.ImageField(
                        blank=True,
                        null=True,
                        upload_to="albums/",
                        verbose_name="Pochette",
                    ),
                ),
                ("release_date", models.DateField(verbose_name="Date de sortie")),
                ("description", models.TextField(blank=True)),
                (
                    "spotify_url",
                    models.URLField(blank=True, verbose_name="Lien Spotify"),
                ),
                (
                    "apple_music_url",
                    models.URLField(blank=True, verbose_name="Lien Apple Music"),
                ),
                ("deezer_url", models.URLField(blank=True, verbose_name="Lien Deezer")),
                (
                    "bandcamp_url",
                    models.URLField(blank=True, verbose_name="Lien Bandcamp"),
                ),
            ],
            options={
                "verbose_name": "Album",
                "verbose_name_plural": "Albums",
                "ordering": ["-release_date"],
            },
        ),
        migrations.CreateModel(
            name="ContactMessage",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=200, verbose_name="Nom")),
                ("email", models.EmailField(max_length=254, verbose_name="Email")),
                ("subject", models.CharField(max_length=300, verbose_name="Sujet")),
                ("message", models.TextField(verbose_name="Message")),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Date d'envoi"
                    ),
                ),
                ("is_read", models.BooleanField(default=False, verbose_name="Lu")),
            ],
            options={
                "verbose_name": "Message de contact",
                "verbose_name_plural": "Messages de contact",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="Event",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "title",
                    models.CharField(
                        max_length=300, verbose_name="Titre / Nom de l'événement"
                    ),
                ),
                ("date", models.DateTimeField(verbose_name="Date et heure")),
                ("venue", models.CharField(max_length=300, verbose_name="Lieu")),
                ("city", models.CharField(max_length=200, verbose_name="Ville")),
                ("description", models.TextField(blank=True)),
                (
                    "ticket_url",
                    models.URLField(blank=True, verbose_name="Lien billetterie"),
                ),
                (
                    "poster",
                    models.ImageField(
                        blank=True,
                        null=True,
                        upload_to="events/",
                        verbose_name="Affiche",
                    ),
                ),
                (
                    "is_cancelled",
                    models.BooleanField(default=False, verbose_name="Annulé"),
                ),
            ],
            options={
                "verbose_name": "Événement / Date",
                "verbose_name_plural": "Événements / Dates",
                "ordering": ["date"],
            },
        ),
        migrations.CreateModel(
            name="Member",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("first_name", models.CharField(max_length=100, verbose_name="Prénom")),
                ("last_name", models.CharField(max_length=100, verbose_name="Nom")),
                (
                    "role",
                    models.CharField(max_length=200, verbose_name="Rôle / Instrument"),
                ),
                (
                    "avatar",
                    models.ImageField(
                        blank=True, null=True, upload_to="members/avatars/"
                    ),
                ),
                ("bio", models.TextField(blank=True, verbose_name="Biographie")),
                (
                    "order",
                    models.PositiveIntegerField(
                        default=0, verbose_name="Ordre d'affichage"
                    ),
                ),
                ("is_active", models.BooleanField(default=True, verbose_name="Actif")),
            ],
            options={
                "verbose_name": "Membre",
                "verbose_name_plural": "Membres",
                "ordering": ["order", "last_name"],
            },
        ),
        migrations.CreateModel(
            name="Page",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "slug",
                    models.SlugField(
                        choices=[
                            ("home", "Accueil"),
                            ("about", "Le groupe"),
                            ("members", "Membres"),
                            ("albums", "Albums"),
                            ("videos", "Vidéos"),
                            ("events", "Dates"),
                            ("contact", "Contact"),
                        ],
                        unique=True,
                    ),
                ),
                (
                    "title",
                    models.CharField(max_length=200, verbose_name="Titre de la page"),
                ),
                (
                    "subtitle",
                    models.CharField(
                        blank=True, max_length=500, verbose_name="Sous-titre"
                    ),
                ),
                (
                    "content",
                    models.TextField(blank=True, verbose_name="Contenu éditorial"),
                ),
                (
                    "banner_image",
                    models.ImageField(
                        blank=True,
                        null=True,
                        upload_to="pages/",
                        verbose_name="Image bannière",
                    ),
                ),
            ],
            options={
                "verbose_name": "Page",
                "verbose_name_plural": "Pages",
            },
        ),
        migrations.CreateModel(
            name="SiteSettings",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("band_name", models.CharField(default="Yes or Not", max_length=200)),
                (
                    "tagline",
                    models.CharField(
                        blank=True, default="Rock / Alternative", max_length=500
                    ),
                ),
                (
                    "about_text",
                    models.TextField(
                        blank=True, verbose_name="Texte de présentation du groupe"
                    ),
                ),
                (
                    "hero_image",
                    models.ImageField(
                        blank=True,
                        null=True,
                        upload_to="site/",
                        verbose_name="Image d'en-tête",
                    ),
                ),
                ("logo", models.ImageField(blank=True, null=True, upload_to="site/")),
                ("facebook_url", models.URLField(blank=True)),
                ("instagram_url", models.URLField(blank=True)),
                ("youtube_url", models.URLField(blank=True)),
                ("spotify_url", models.URLField(blank=True)),
                (
                    "email_contact",
                    models.EmailField(
                        blank=True, default="contact@yesornot.fr", max_length=254
                    ),
                ),
            ],
            options={
                "verbose_name": "Paramètres du site",
                "verbose_name_plural": "Paramètres du site",
            },
        ),
        migrations.CreateModel(
            name="Video",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=200, verbose_name="Titre")),
                (
                    "embed_url",
                    models.URLField(verbose_name="URL d'intégration (embed)"),
                ),
                ("description", models.TextField(blank=True)),
                (
                    "thumbnail",
                    models.ImageField(
                        blank=True,
                        null=True,
                        upload_to="videos/",
                        verbose_name="Miniature",
                    ),
                ),
                (
                    "published_date",
                    models.DateField(
                        blank=True, null=True, verbose_name="Date de publication"
                    ),
                ),
                (
                    "is_featured",
                    models.BooleanField(default=False, verbose_name="Mise en avant"),
                ),
                ("order", models.PositiveIntegerField(default=0)),
            ],
            options={
                "verbose_name": "Vidéo",
                "verbose_name_plural": "Vidéos",
                "ordering": ["order", "-published_date"],
            },
        ),
        migrations.CreateModel(
            name="MemberPortfolioItem",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=200, verbose_name="Titre")),
                ("description", models.TextField(blank=True)),
                (
                    "image",
                    models.ImageField(
                        blank=True, null=True, upload_to="members/portfolio/"
                    ),
                ),
                (
                    "video_url",
                    models.URLField(
                        blank=True, verbose_name="URL vidéo (YouTube, etc.)"
                    ),
                ),
                ("order", models.PositiveIntegerField(default=0)),
                (
                    "member",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="portfolio_items",
                        to="band.member",
                    ),
                ),
            ],
            options={
                "verbose_name": "Élément de portfolio",
                "verbose_name_plural": "Éléments de portfolio",
                "ordering": ["order"],
            },
        ),
        migrations.CreateModel(
            name="Track",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=200, verbose_name="Titre")),
                (
                    "track_number",
                    models.PositiveIntegerField(verbose_name="N° de piste"),
                ),
                (
                    "duration",
                    models.CharField(
                        blank=True, max_length=10, verbose_name="Durée (ex: 3:45)"
                    ),
                ),
                (
                    "album",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="tracks",
                        to="band.album",
                    ),
                ),
            ],
            options={
                "verbose_name": "Piste",
                "verbose_name_plural": "Pistes",
                "ordering": ["track_number"],
            },
        ),
    ]
