# Generated by Django 5.2.11 on 2026-02-08 18:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("band", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="member",
            options={
                "ordering": ["order", "first_name"],
                "verbose_name": "Membre",
                "verbose_name_plural": "Membres",
            },
        ),
        migrations.AlterField(
            model_name="member",
            name="last_name",
            field=models.CharField(
                blank=True, default="", max_length=100, verbose_name="Nom"
            ),
        ),
    ]
