# Generated by Django 5.2.11 on 2026-02-08 18:58

import django_ckeditor_5.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("band", "0002_alter_member_options_alter_member_last_name"),
    ]

    operations = [
        migrations.AlterField(
            model_name="album",
            name="description",
            field=django_ckeditor_5.fields.CKEditor5Field(blank=True),
        ),
        migrations.AlterField(
            model_name="event",
            name="description",
            field=django_ckeditor_5.fields.CKEditor5Field(blank=True),
        ),
        migrations.AlterField(
            model_name="member",
            name="bio",
            field=django_ckeditor_5.fields.CKEditor5Field(
                blank=True, verbose_name="Biographie"
            ),
        ),
        migrations.AlterField(
            model_name="memberportfolioitem",
            name="description",
            field=django_ckeditor_5.fields.CKEditor5Field(blank=True),
        ),
        migrations.AlterField(
            model_name="page",
            name="content",
            field=django_ckeditor_5.fields.CKEditor5Field(
                blank=True, verbose_name="Contenu éditorial"
            ),
        ),
        migrations.AlterField(
            model_name="sitesettings",
            name="about_text",
            field=django_ckeditor_5.fields.CKEditor5Field(
                blank=True, verbose_name="Texte de présentation du groupe"
            ),
        ),
        migrations.AlterField(
            model_name="video",
            name="description",
            field=django_ckeditor_5.fields.CKEditor5Field(blank=True),
        ),
    ]
