# Generated by Django 5.2.11 on 2026-02-08 19:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("band", "0004_memberphoto"),
    ]

    operations = [
        migrations.AddField(
            model_name="track",
            name="audio_file",
            field=models.FileField(
                blank=True,
                null=True,
                upload_to="albums/tracks/",
                verbose_name="Fichier audio (MP3)",
            ),
        ),
    ]
