# Generated by Django 5.2.11 on 2026-02-08 22:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("band", "0005_track_audio_file"),
    ]

    operations = [
        migrations.AddField(
            model_name="video",
            name="video_file",
            field=models.FileField(
                blank=True,
                help_text="Télécharger un fichier MP4. Si rempli, sera utilisé à la place du lien embed.",
                null=True,
                upload_to="videos/mp4/",
                verbose_name="Fichier vidéo (MP4)",
            ),
        ),
        migrations.AlterField(
            model_name="video",
            name="embed_url",
            field=models.URLField(
                blank=True, verbose_name="URL d'intégration (embed YouTube)"
            ),
        ),
    ]
