# Generated by Django 5.2.11 on 2026-02-09 06:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("band", "0006_video_video_file_alter_video_embed_url"),
    ]

    operations = [
        migrations.CreateModel(
            name="EventMedia",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "media_type",
                    models.CharField(
                        choices=[("photo", "Photo"), ("video", "Vidéo")],
                        default="photo",
                        max_length=10,
                        verbose_name="Type",
                    ),
                ),
                (
                    "image",
                    models.ImageField(
                        blank=True,
                        null=True,
                        upload_to="events/gallery/",
                        verbose_name="Photo",
                    ),
                ),
                (
                    "video_file",
                    models.FileField(
                        blank=True,
                        null=True,
                        upload_to="events/gallery/videos/",
                        verbose_name="Fichier vidéo (MP4)",
                    ),
                ),
                (
                    "caption",
                    models.CharField(
                        blank=True, max_length=300, verbose_name="Légende"
                    ),
                ),
                ("order", models.PositiveIntegerField(default=0, verbose_name="Ordre")),
                (
                    "event",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="media",
                        to="band.event",
                    ),
                ),
            ],
            options={
                "verbose_name": "Média de l'événement",
                "verbose_name_plural": "Galerie média",
                "ordering": ["order"],
            },
        ),
    ]
