# Generated by Django 5.2.11 on 2026-02-09

from django.db import migrations, models
from django.utils.text import slugify


def populate_slugs(apps, schema_editor):
    Event = apps.get_model("band", "Event")
    used_slugs = set()
    for event in Event.objects.all().order_by("date"):
        base_slug = slugify(event.title) or "evenement"
        slug = base_slug
        n = 1
        while slug in used_slugs:
            slug = f"{base_slug}-{n}"
            n += 1
        event.slug = slug
        event.save(update_fields=["slug"])
        used_slugs.add(slug)


class Migration(migrations.Migration):

    dependencies = [
        ("band", "0007_eventmedia"),
    ]

    operations = [
        # Step 1: add slug field without unique constraint (db_index=False
        # to avoid creating _like index that conflicts with step 3's unique)
        migrations.AddField(
            model_name="event",
            name="slug",
            field=models.SlugField(
                blank=True,
                db_index=False,
                default="",
                help_text="Généré automatiquement à partir du titre. Modifiable.",
                max_length=350,
                verbose_name="Slug URL",
            ),
            preserve_default=False,
        ),
        # Step 2: populate slugs for existing events
        migrations.RunPython(populate_slugs, migrations.RunPython.noop),
        # Step 3: make slug unique
        migrations.AlterField(
            model_name="event",
            name="slug",
            field=models.SlugField(
                blank=True,
                help_text="Généré automatiquement à partir du titre. Modifiable.",
                max_length=350,
                unique=True,
                verbose_name="Slug URL",
            ),
        ),
    ]
