# Generated by Django 5.2.11 on 2026-02-09 08:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("band", "0008_event_slug"),
    ]

    operations = [
        migrations.CreateModel(
            name="Song",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=300, verbose_name="Titre")),
                ("artist", models.CharField(max_length=300, verbose_name="Artiste")),
                (
                    "youtube_url",
                    models.URLField(blank=True, verbose_name="URL YouTube"),
                ),
                (
                    "audio_file",
                    models.FileField(
                        blank=True,
                        help_text="Fichier MP3 du morceau",
                        null=True,
                        upload_to="songs/mp3/",
                        verbose_name="Enregistrement MP3",
                    ),
                ),
                ("notes", models.TextField(blank=True, verbose_name="Notes")),
            ],
            options={
                "verbose_name": "Morceau (répertoire)",
                "verbose_name_plural": "Morceaux (répertoire)",
                "ordering": ["artist", "title"],
                "unique_together": {("title", "artist")},
            },
        ),
        migrations.CreateModel(
            name="SetlistEntry",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "position",
                    models.PositiveIntegerField(verbose_name="Ordre de passage"),
                ),
                (
                    "event",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="setlist_entries",
                        to="band.event",
                    ),
                ),
                (
                    "song",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="setlist_entries",
                        to="band.song",
                    ),
                ),
            ],
            options={
                "verbose_name": "Morceau de la setlist",
                "verbose_name_plural": "Setlist",
                "ordering": ["position"],
                "unique_together": {("event", "position"), ("event", "song")},
            },
        ),
    ]
