# Generated by Django 5.2.11 on 2026-02-09 09:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("band", "0009_song_setlistentry"),
    ]

    operations = [
        migrations.AddField(
            model_name="song",
            name="lyrics",
            field=models.TextField(blank=True, verbose_name="Paroles"),
        ),
        migrations.CreateModel(
            name="SheetMusic",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "instrument",
                    models.CharField(max_length=200, verbose_name="Instrument"),
                ),
                (
                    "file",
                    models.FileField(
                        help_text="Partition au format PDF ou image",
                        upload_to="songs/sheets/",
                        verbose_name="Fichier (PDF, image…)",
                    ),
                ),
                (
                    "song",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="sheets",
                        to="band.song",
                    ),
                ),
            ],
            options={
                "verbose_name": "Partition",
                "verbose_name_plural": "Partitions",
                "ordering": ["instrument"],
                "unique_together": {("song", "instrument")},
            },
        ),
    ]
