# Generated by Django 5.2.11 on 2026-02-09 09:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("band", "0010_song_lyrics_sheetmusic"),
    ]

    operations = [
        migrations.CreateModel(
            name="Instrument",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(max_length=200, unique=True, verbose_name="Nom"),
                ),
                (
                    "order",
                    models.PositiveIntegerField(
                        default=0, verbose_name="Ordre d'affichage"
                    ),
                ),
            ],
            options={
                "verbose_name": "Instrument",
                "verbose_name_plural": "Instruments",
                "ordering": ["order", "name"],
            },
        ),
        migrations.AlterModelOptions(
            name="sheetmusic",
            options={
                "ordering": ["instrument__order", "instrument__name"],
                "verbose_name": "Partition",
                "verbose_name_plural": "Partitions",
            },
        ),
        migrations.AlterField(
            model_name="sheetmusic",
            name="instrument",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to="band.instrument",
                verbose_name="Instrument",
            ),
        ),
    ]
