# Generated by Django 5.2.11 on 2026-02-09 09:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("band", "0011_instrument_alter_sheetmusic_options_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="song",
            name="duration",
            field=models.CharField(
                blank=True, max_length=10, verbose_name="Durée (ex: 3:45)"
            ),
        ),
    ]
