# Generated by Django 5.2.11 on 2026-02-09 12:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("band", "0012_song_duration"),
    ]

    operations = [
        migrations.CreateModel(
            name="Artist",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(max_length=300, unique=True, verbose_name="Nom"),
                ),
            ],
            options={
                "verbose_name": "Artiste",
                "verbose_name_plural": "Artistes",
                "ordering": ["name"],
            },
        ),
        migrations.AlterField(
            model_name="song",
            name="artist",
            field=models.CharField(max_length=300, verbose_name="Artiste (ancien)"),
        ),
        migrations.AddField(
            model_name="song",
            name="artist_link",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="songs",
                to="band.artist",
                verbose_name="Artiste",
            ),
        ),
    ]
